version: '3'

services:
  neuromansui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./outputs:/app/outputs
    command:
      - "--prompt"
      - "sui_move.base_contract"
      - "--module-name"
      - "my_module"
      - "--save-dir"
      - "/app/outputs"
      - "--generate-tests"
      - "--save-iterations"

  neuromansui-server:
    build: .
    volumes:
      - ./outputs:/app/outputs
    ports:
      - "3000:3000"
    command: --server
    entrypoint: ["/bin/bash", "/app/start-server.sh"] 